---
editor:
    render-on-save: true
bibliography: references.bib
csl: ieee.csl
---

Understanding how genotypes encode phenotypes that allow organisms to survive
and reproduce in different environments is one of the central challenges for
modern evolutionary biology [@Lassig2017; @manrubia2021]. Although the field has
seen a surge in predictive modeling being deployed in real-world applications
ranging from viral dynamics [@uksza2014] to cancer immunotherapy [@luksza2017],
it is still unclear to what extent evolutionary trajectories under different
environmental pressures can be predicted. Two main challenges make this question
difficult to answer. First, the vast number of genetic changes available to a
population makes it impossible to exhaustively sample and measure the phenotypic
consequences of each mutation [@louis2016]. Second, for most but a few simple
model systems, it is unknown what the phenotypic changes driving adaptation are
[*cite?*].

Nevertheless, advances in modern high-throughput technologies have made it
possible to measure the fitness of multiple genotypes, opening up the
possibility of extracting valuable information about the
genotype-phenotype-fitness map from these datasets [@kinsler2020; @maeda2020;
@iwasawa2022; @ascensao2023]. Moreover, an extensive body of empirical studies
and theoretical work has suggested that the dynamics of adaptation are highly
constrained, making them potentially predictable [@weinreich2006; @wagner2008;
@louis2016; @furusawa2018]. 

<!-- Inspired by this body of work and the deep-learning revolution with the capacity
to extract simple patterns from complex high-dimensional data, we set out two
main goals for this work: 1. to develop a simple theoretical framework to
capture the qualitative features of the data generative process of
high-throughput fitness assays, and 2. to connect this framework with a
data-driven non-linear dimensionality reduction method to extract relevant
features from such complex high-dimensional datasets. -->

Inspired by this body of work and the impressive results that the deep-learning
revolution has achieved in the life sciences [@martin2024], we set out to
develop a data-driven framework to uncover the underlying structure of the
genotype-phenotype-fitness landscape from high-throughput fitness data. We
consider three main ingredients for a computational method to tackle this
challenge:

1.  The method should be able to take advantage of the data-rich landscape of
modern biology, where high-throughput fitness measurements are becoming
increasingly common [@kinsler2020; @maeda2020; @iwasawa2022; @ascensao2023].

2. It should be able to uncover the potentially hidden simplicity in the
structure of the high-dimensional datasets generated by these experiments by
projecting them in a principled way into a lower-dimensional space visualizable
by humans.

3. The generated low-dimensional map should be accompanied by the corresponding
geometric information on how the high-dimensional space is folded into the map,
making the distances on the map meaningful in the high-dimensional space.

Here, we propose the use of a geometry-aware variational autoencoder---a neural
network architecture that embeds high-dimensional data into a low-dimensional
space while simultaneously learning the geometric transformations that map the
learned low-dimensional space back into the high-dimensional space via a metric
tensor [@chadebec2020]. To validate the applicability of this method to
high-dimenional fitness data, we develop a simple model of adaptive dynamics
that captures the main qualitative features of the data generated by
high-throughput fitness assays. In this model, multiple lineages perform a
biased random walk on a low-dimensional phenotypic space towards regions of
higher fitness, defined by the environment-specific topology of the fitness
landscape. Changing the environment, therefore, amounts to changing the
landscape topology while keeping the phenotypic coordinates of the lineages
constant. We show that the geometry-aware variational autoencoder (hereafter
*RHVAE* for Riemannian Hamiltonian Variational Autoencoder [@chadebec2020]) is
able to learn a low-dimensional embedding that retains information about the
relative positions of the simulated lineages in the original phenotypic space.
Furthermore, we show that adaptive trajectories projected onto the learned
low-dimensional embedding are highly predictable. 

We then apply this method to a dataset of high-throughput fitness measurements
of *E. coli* under different antibiotic pressures [@iwasawa2022]. We show that
the *RHVAE* is also able to learn a low-dimensional embedding that captures the
main adaptive trajectories in the dataset, suggesting that the method can serve
as a powerful exploratory tool to uncover the underlying structure of the hidden
phenotypic space in which adaptive dynamics unfold, given only high-throughput
fitness data. Taken together, our results suggest that high-dimensional fitness
data---such as the one studied here in *E. coli*---can reveal hidden simplicity
in the evolutionary dynamics when analyzed with the right computational
framework.