---
editor:
    render-on-save: true
bibliography: references.bib
csl: ieee.csl
---

## Simple Phenotype-Fitness Model

With the advent of high-throughput fitness assays, determining the fitness of
multiple genotypes in a plethora of different environments has become a routine
procedure in biology [@kinsler2020; @maeda2020; @iwasawa2022; @ascensao2023].
Nevertheless, we argue that we still lack a simple conceptual framework to guide
our interpretation of the patterns observed in these datasets. To that end, we
propose a simple model of phenotype-fitness dynamics to serve as a guidepost for
our interpretation of the data. 

@fig-01(A) shows a schematic of the genotype-phenotype-fitness map. A genotype
$g$ produces a set of measurable traits or phenotypes $\underline{p}$---depicted
as two potential molecular phenotypes, such as an efflux pump rate and the
sensitivity of a membrane receptor. The fitness of each genotype is determined
by the value of these phenotypes and the environment $E$---depicted as the
doubling time of a bacterial population. To formalize this mathematically, we
represent genotypes as points in a multi-dimensional phenotypic space, where
each dimension is a different trait ($\underline{p} \in \mathbb{R}^P$, where $P$
is the number of traits). Thus, any genotype $g$ has a unique mapping to a
phenotypic coordinate. However, this mapping is not necessarily bijective, i.e.,
multiple genotypes may map to the same phenotype. To represent the likelihood of
sampling some genotype $g$ that maps to some coordinate $\underline{p}$ in
phenotype space, we introduce a genotype-to-phenotype density map $GP$ that
takes a given phenotypic coordinate $\underline{p}$ and returns a number
proportional to the probability of sampling a genotype $g$ that maps to
$\underline{p}$. This function captures the empirical observation that the
genotype-to-phenotype map is highly redundant, with many genotypes mapping to
equivalent phenotypes and some phenotypes being extremely rare [@louis2016].
@fig-01(B, left) shows a schematic of one possible $GP$ map overlaid on a 2D
phenotype space. For illustration purposes, we set the $GP$ map to contain four
negative Gaussian peaks, representing four regions of the phenotype space that
are unlikely to be sampled (see Supplementary Material for a more detailed
discussion). The location and size of these peaks are assumed to be fixed by the
genotype-to-phenotype map, irrespective of the environment. Finally, we
introduce a fitness function $F$ that maps a phenotypic coordinate
$\underline{p}$ to a fitness value in a particular environment. We assume the
topography of the fitness landscape (the number, size, and position of fitness
peaks) is determined by the environment $E$. @fig-01(B, right) shows a schematic
of a simple fitness landscape with a single symmetric Gaussian peak.

In recent experimental evolution studies, genotypes are evolved under a fixed
environment, but the fitness is measured across multiple environments
[@kinsler2020;@iwasawa2022]. To reflect this, @fig-01(C) shows the effect of
changing the environment on the phenotype-fitness map. Even though the mapping
from genotype to phenotype (coordinates of the example points) and the
genotype-to-phenotype density map (white contours) are invariant to the
environment, the fitness landscape (black dashed contours) changes as the
environment varies. We model this by changing the topography of the fitness map
in terms of the number, position, height, and width of the Gaussian peaks.
Therefore, we conceptualize the measured fitness profiles on multiple
environments as measuring the heights of a fixed phenotypic coordinate on
multiple fitness landscapes. @fig-01(D) shows the equivalent experimental
observable---the fitness values of any genotype $g$ on multiple environments,
hereafter referred to as a fitness profile. We ask whether extracting
information about the latent phenotypic coordinates is possible based only on
such high-dimensional fitness profiles. Conceptually, this is equivalent to
asking whether it is possible to reverse the mapping from phenotypes to fitness
values and predict the phenotypic coordinates of a genotype based only on its
fitness values across multiple environments.

![**Model of phenotype-fitness dynamics**. (A) Schematic of the
genotype-phenotype-fitness map. A pair of genotypes $g^{(\text{b})}$ and
$g^{(\text{r})}$ are shown. These genotypes map to two relevant phenotypes $p_1$
and $p_2$ via a function $\phi$. The fitness of each genotype is determined by
the value of these phenotypes and their relevance in the environment via a
function $F$. (B) Phenotype space functions. Left: The genotype-to-phenotype
density map $GP$ where the probability of observing a phenotype $\underline{p}$
is shown as a function of the phenotype values $p_1$ and $p_2$. White lines show
iso-probability contours. Right: The fitness landscape $F$ as a function of the
phenotype values $p_1$ and $p_2$. White lines show iso-fitness contours. The
points show the coordinates of the two genotypes in phenotype space. (C)
Examples of the effect of changing the environment on the phenotype-fitness
landscape. The phenotypic coordinates of any genotype and the
genotype-to-phenotype density map are not affected by changes in the
environment. The fitness landscape, however, does change as the environment
changes. Green landscape shows the evolution condition where selection happens.
Gray landscapes show other environments with different topographies (position,
number, and height of fitness peaks). Black dashed lines indicate fitness
landscape contours, while white solid lines show genotype-phenotype density
contours. (D) Fitness profiles. The fitness values of any genotype measured
across multiple environments represent an experimental
observable.](./fig/main/fig01_v06_compiled){#fig-01}