---
editor:
    render-on-save: true
bibliography: references.bib
csl: ieee.csl
---

## Evolutionary Dynamics on Phenotype Space

Having defined a simple phenotype-fitness model, we now instantiate a set of
rules for evolutionary dynamics on this phenotypic space. We implement a simple
model that captures two key features of evolutionary processes: the tendency of
populations to move towards higher fitness and the constraints imposed by the
accessibility of different phenotypes. We frame evolution as a biased random
walk where each step is influenced by both the fitness landscape
$F(\underline{p})$ and the genotype-phenotype density $GP(\underline{p})$.

At each time step, the population can transition from its current phenotype
$\underline{p}$ to a new phenotype $\underline{p}'$, where the proposed
phenotype $\underline{p}'$ is drawn from a proposal distribution
$q(\underline{p}' \mid \underline{p})$. Whether this transition
occurs---equivalent to the mutation being fixed in the population---depends on
the relative fitness of the new phenotype and how easily it can be reached
through mutations. Specifically, as derived in the Supplementary Materials section B, the
probability of accepting a transition is given by

$$
\textcolor{customred}{
P_{\text{accept}} = \min\left(
    1,
    \frac{F(\underline{p}')^{\beta_F} GP(\underline{p}')^{\beta_{GP}}}
    {F(\underline{p})^{\beta_F} GP(\underline{p})^{\beta_{GP}}}
\right),
}
$${#eq-acceptance-probability}

<span style="color: #912E27;">
where $\beta_F$ and $\beta_{GP}$ are parameters that separately control the
balance between selection and drift. These parameters can be interpreted as the
strength of selection and the inaccessibility of certain phenotypes,
respectively---higher values of $\beta_F$ lead to more deterministic
trajectories that closely follow fitness gradients, while lower values allow for
more stochastic exploration of the phenotype space. In a similar fashion, higher
values of $\beta_{GP}$ lead to trajectories that avoid low genotype-to-phenotype
density regions with higher probability. Detailed mathematical derivations and
analysis of this algorithm can be found in the Supplementary Materials section
B. For simplicity, in this work we make the simplifying assumption that $\beta_F
= \beta_{GP} = \beta$, as this was sufficient to explore the effects of varying
evolutionary stochasticity on the overall landscape.
</span>

This formulation represents a simplified model of evolutionary dynamics with
specific assumptions: First, transitions to phenotypes with higher fitness are
more likely to be fixed, reflecting selection's influence in our model, though
in natural populations even beneficial mutations may be lost due to drift and
other factors. Second, transitions to lower fitness phenotypes can occur with
some probability, incorporating stochastic elements of evolution. Finally, the
$GP(\underline{p})$ term accounts for the mutational accessibility of
phenotypes—phenotypes requiring rare genetic variants are less likely to be
reached even if highly fit. This approach draws on elements from adaptive
dynamics and Metropolis-Hastings algorithms applied to evolutionary processes.
@fig-02(A, top) shows example trajectories in phenotypic space of multiple
lineages evolving on a simple single-peaked fitness landscape. @fig-02(A,
bottom) shows the fitness trajectory of these evolving lineages over time, i.e.,
the equivalent of the experimental observable we can access in a laboratory
setting. When we examine these same phenotypic trajectories under different
environmental conditions (@fig-02(B)), we observe that, as expected, while the
path through phenotype space remains fixed, the fitness values we measure vary
because each environment imposes its unique fitness landscape. The fitness
values in all environments for a given lineage at a given time point define one
fitness profile, as the ones depicted in @fig-01(D). As shown in the
Supplementary Materials section K, our main results using a more detailed population
genetics framework yielded consistent conclusions. 

In what follows, we use synthetic data generated from this model, where ten
lineages (initial phenotype coordinates) in two replicates (different
instantiations of the random dynamics) evolve for 300 time steps on 50 different
fitness landscapes (different topographies, meaning number, position, and
relative height of fitness peaks). For each of these conditions, the fitness in
all other environments is also determined, giving a high-dimensional dataset
analogous to the ones in recent experimental studies [@kinsler2020;
@iwasawa2022; @ascensao2023; @ghosh2025]. We use this dataset to test whether it
is possible to reverse the mapping from phenotypes to fitness values and
reconstruct the phenotypic coordinates of a genotype based only on fitness
profiles.

![**Evolutionary dynamics on phenotype space**. (A) Top: Metropolis-like
evolutionary dynamics on phenotype space. Each line represents the trajectory of
a lineage as it evolves over time, with crosses and triangles denoting the
initial phenotypic coordinate of a few selected lineages. Note that trajectories
tend to move towards higher fitness values, avoiding low genotype-to-phenotype
density regions. Bottom: Fitness over time of the same trajectories shown above.
(B) The same trajectories shown in (A) overlaid on different fitness maps
determined by different environments. Although the phenotypic coordinates of the
genotypes remain the same (top panels), the resulting fitness readouts change as
the topography of the environment-dependent fitness landscape changes (bottom
panels).](./fig/main/fig02_v05){#fig-02}