---
editor:
    render-on-save: true
bibliography: references.bib
csl: ieee.csl
---

## Simple Phenotype-Fitness Model

With the advent of high-throughput fitness assays, determining the fitness of
multiple genotypes on a plethora of different environments has become a routine
procedure in evolutionary biology [@kinsler2020; @maeda2020; @iwasawa2022;
@ascensao2023]. Nevertheless, we argue that we still lack a simple conceptual
framework to guide our interpretation of the patterns observed in these
datasets. To that end, we propose a simple model of phenotype-fitness dynamics
to serve as a light post for our interpretation of the data. 

@fig-01(A) shows a schematic of the genotype-phenotype-fitness map. A genotype
$g$ is mapped to a phenotype coordinate $\underline{p}$ via a function $\phi$.
The fitness of each genotype is determined by the value of these phenotypes and
the environment $E$ via a function $F$. To operationalize this model, we assume
that phenotypes can be described by a vector of $P$ real-valued variables,
$\underline{p} \in \mathbb{R}^P$. Thus, phenotypic space is a $P$-dimensional
Euclidean space, and any genotype $g$ has a unique mapping to a phenotypic
coordinate. However, this mapping is not necessarily bijective, i.e., multiple
genotypes may map to the same phenotype. To represent the likelihood of sampling
some genotype $g$ that maps to some coordinate $\underline{p}$ in phenotype
space, we introduce a genotype-to-phenotype density map $GP: \mathbb{R}^P \to
\mathbb{R}$. This function captures the empirical observation that the
genotype-to-phenotype map is highly redundant, with many genotypes mapping to
equivalent phenotypes and some phenotypes being extremely rare [@louis2016].
@fig-01(B, left) shows a schematic of one possible $GP$ map overlaid on a 2D
phenotype space. For illustration purposes, we set the $GP$ map to contain four
negative Gaussian peaks, which represent four regions of the phenotype space
that are unlikely to be sampled (see @sec-metropolis in the supplementary
material for a more detailed discussion). The fitness function $F: \mathbb{R}^P
\to \mathbb{R}$ is also assumed to be a function of the phenotype values.
However, the topology of the fitness landscape is determined by the environment
$E$. @fig-01(B, right) shows a schematic of the simplest fitness landscape with
a single symmetric Gaussian peak.

In multiple experimental evolution studies, genotypes are evolved under a fixed
environment, but the fitness is measured on multiple environments
[@kinsler2020;@iwasawa2022]. To reflect this, @fig-01(C) shows the effect of
changing the environment on the phenotype-fitness map. Even though the mapping
from genotype to phenotype and the genotype-to-phenotype density map are
invariant to the environment, the fitness landscape changes as the environment
varies. We model this by changing the topology of the fitness map in terms of
the number, position, height, and width of the Gaussian peaks. Therefore, we
conceptualize the measured fitness profiles on multiple environments as
measuring the heights of a fixed phenotypic coordinate on multiple fitness
landscapes. The challenge, then, is to extract information about these latent
phenotypic coordinates from such high-dimensional fitness measurements.

![**Model of phenotype-fitness dynamics**. (A) Schematic of the
genotype-phenotype-fitness map. A pair of genotypes $g^{(\text{b})}$ and
$g^{(\text{r})}$ are shown. These genotypes map to two relevant phenotypes $p_1$
and $p_2$ via a function $\phi$. The fitness of each genotype is determined by
the value of these phenotypes and their relevance in the environment via a
function $F$. (B) Phenotype space functions. Left: The genotype-to-phenotype
density map $GP$ where the probability of observing a phenotype $\underline{p}$
is shown as a function of the phenotype values $p_1$ and $p_2$. White lines show
iso-probability contours. Right: The fitness landscape $F$ as a function of the
phenotype values $p_1$ and $p_2$. White lines show iso-fitness contours. The
points show the coordinates of the two genotypes in phenotype space. (C)
Examples of the effect of changing the environment on the phenotype-fitness
landscape. The phenotypic coordinates of any genotype as well as the
genotype-to-phenotype density map are not affected by changes of the
environment. The fitness landscape, however, does change as the environment
changes. Green landscape shows the evolution condition where selection happens.
Gray landscapes show other environments with different topologies. Black dashed
lines indicate fitness landscape contours, while white solid lines show
genotype-phenotype density contours.](./fig/main/fig01_v05_compiled){#fig-01}

