::: {.abstract}

::: {.content-visible when-format="html"}
<div class="block-title">Abstract</div>
:::

Elucidating the complex relationships between genotypes, phenotypes, and fitness
remains one of the fundamental challenges in evolutionary biology. Part of the
difficulty arises from the enormous number of possible genotypes and the lack of
understanding of the underlying phenotypic differences driving adaptation. Here,
we present a computational method that takes advantage of modern high-throughput
fitness measurements to learn a map from high-dimensional fitness profiles to a
low-dimensional latent space in a geometry-informed manner. We demonstrate that
our approach using a Riemannian Hamiltonian Variational Autoencoder (RHVAE)
outperforms traditional linear dimensionality reduction techniques by capturing
the nonlinear structure of the phenotype-fitness map. When applied to simulated
adaptive dynamics, we show that the learned latent space retains information
about the underlying adaptive phenotypic space and accurately reconstructs
complex fitness landscapes. We then apply this method to a dataset of
high-throughput fitness measurements of *E. coli* under different antibiotic
pressures and demonstrate superior predictive power for out-of-sample data
compared to linear approaches. Our work provides a data-driven implementation of
Fisher's geometric model of adaptation, transforming it from a theoretical
framework into an empirically grounded approach for understanding evolutionary
dynamics using modern deep learning methods. 
:::
::: {.maintext}

# Introduction

{{< include _00intro.qmd >}}

# Results

<!-- Model framework -->
{{< include _01model_framework.qmd >}}

<!-- Evolutionary dynamics -->
{{< include _02evolutionary_dynamics.qmd >}}

<!-- Latent space geometry -->
{{< include _03latent_space_geometry.qmd >}}

<!-- Latent space simulation -->
{{< include _04latent_space_simulation.qmd >}}

<!-- Fitness landscapes -->
{{< include _05fitness_landscapes_sim.qmd >}}

<!-- Antibiotic data -->
{{< include _06antibiotic_data.qmd >}}

<!-- Cross-validation -->
{{< include _07crossvalidation.qmd >}}

# Discussion

{{< include _discussion.qmd >}}

# Data and code availability {.unnumbered}

All data and custom scripts were collected and stored using Git version control.
Code for raw data processing, theoretical analysis, and figure generation is
available on the [GitHub
repository](https://github.com/mrazomej/antibiotic_landscape)

# Acknowledgements {.unnumbered}

{{< include _acknowledgements.qmd >}}
:::

::: {.content-visible when-format="pdf"}
::: {.sitext}
# Supplementary Materials {.unnumbered}
<!-- notes on Bayesian inference -->
{{< include _bayes_ic50.qmd >}}

<!-- notes on Metropolis-Hastings -->
{{< include _metropolis.qmd >}}

<!-- notes on RHVAE -->
{{< include _rhvae.qmd >}}

<!-- notes on nonlinear manifolds -->
{{< include _nonlinear_manifolds.qmd >}}

<!-- notes on cross-validation -->
{{< include _crossvalidation.qmd >}}

<!-- notes on geodesics -->
{{< include _geodesics.qmd >}}

<!-- notes on fitness landscapes -->
{{< include _fitness_landscapes_data.qmd >}}

<!-- notes on Neural Geodesic -->
{{< include _architecture.qmd >}}

<!-- notes on latent space alignment -->
{{< include _latent_align.qmd >}}

<!-- notes on Metropolis-Kimura -->
{{< include _metropolis_kimura.qmd >}}
:::
:::
